query UserHero($userUuid: String!) {
  userHero(userUuid: $userUuid) {
    uuid
    name
    email
    contacts {
      displayText
      iconPath
      link
      title
      type
      uuid
    }
    heroGreetings {
      content
      device
      footer
      title
      uuid
    }
    navLinks {
      className
      content
      language
      url
      uuid
    }
  }
}
