query UserHero($userUuid: String!) {
  userHero(userUuid: $userUuid) {
    uuid
    email
    firstName
    lastName
    username
    picture
    contacts {
      displayText
      iconName
      link
      title
      type
      uuid
      className
    }
    heroGreetings {
      content
      device
      footer
      title
      uuid
    }
    navLinks {
      className
      content
      language
      url
      uuid
    }
    payments {
      displayText
      isFavorite
      link
      title
      paymentSource {
        logoPath
        website
        name
      }
    }
  }
}
