mutation signIn($email: String!, $password: String!) {
  signIn(email: $email, password: $password) {
    access_token
  }
}

mutation createUser($data: UserCreateInput!) {
  createUser(data: $data) {
    uuid
    createdAt
  }
}
