export const config = {
  motivationalMessages: [
    "You rock!",
    "Keep shining!",
    "Crushing it!",
    "Code like a boss!",
    "You got this, champ!",
    "Slay the day!",
    "Dev power!",
    "Fuel the hustle!",
    "Built to win!",
    "Hack the limits!",
    "Own the code!",
    "Ship it!",
    "Level up!",
    "Stay awesome!",
    "You’re fire! 🔥"
  ],
  CURSOR: "|",
  PROMPT_ICON: "$",
  FULL_TEXT: "git checkout dev ↵",
  RELOAD_ICON: "⟳",
  CLOSE_ICON: "✖",
  MINIMIZE_ICON: "—",
  MAXIMIZE_ICON: "▢",
  WELCOME: "Welcome to LucoDev!",
  TYPING_INTERVAL: 150,
  HIDE_TEXT_DELAY: 500,
  SCREEN_READER_LABEL: "LucoDev",
  FIRST_WORD: "luco",
  SECOND_WORD: "dev",
  SHOW_GREETING_SCROLL_Y: 195,
  TYPED_TEXT_LENGTH: 10,
  INITIAL_OPACITY: 0.5,
  FINAL_OPACITY: 1,
  TRANSITION_DURATION: 300,
  CONTAINER_CLASSES: "w-fit px-1 py-0 md:px-4 md:py-2 font-mono border-4 border-t-0 rounded-b-xl bg-gradient-to-r from-blue-100 via-white to-pink-100 border-blue-500 shadow-lg transition-opacity duration-300",
  TEXT_CLASSES: "text-2xl md:text-4xl tracking-tight",
  FIRST_WORD_CLASSES: "text-pink-500 drop-shadow-sm font-bold",
  SECOND_WORD_CLASSES: "text-blue-500"
};