services:
  flyway:
    container_name: sb_flyway
    image: flyway/flyway:latest
    environment:
      - FLYWAY_URL=jdbc:postgresql://ep-snowy-bread-adrndmuv-pooler.c-2.us-east-1.aws.neon.tech/portfolio?sslmode=require&channel_binding=require
      - FLYWAY_USER=neondb_owner
      - FLYWAY_PASSWORD=npg_BUrsKMi7Q2Lu
      - FLYWAY_SCHEMAS=public
      - FLYWAY_CONNECT_RETRIES=60
      - FLYWAY_CONNECT_RETRIES_INTERVAL=10
      - FLYWAY_VALIDATE_ON_MIGRATE=true
      - FLYWAY_CLEAN_DISABLED=false
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_BASELINE_VERSION=1.0.0
    command: >
      -locations=filesystem:/flyway/migrations
      -loggers=console
      migrate
    volumes:
      - ./migrations:/flyway/migrations:ro
      - ./logs:/flyway/logs
    networks:
      - flyway_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "flyway info || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  flyway_network:
    driver: bridge

volumes:
  flyway_logs:
    driver: local