import { Geist, Geist_Mono } from 'next/font/google';
import type { Metadata } from 'next';
import { RootLayoutClient } from './layout-client';
import { ApolloWrapper } from '@/lib/ApolloWrapper';
import '../globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'VIZ admin',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}>
        <ApolloWrapper>
          <RootLayoutClient>{children}</RootLayoutClient>
        </ApolloWrapper>
      </body>
    </html>
  );
}
